name: Pre-commit Check

on:
  workflow_dispatch:
    paths:
      - '**.py'  
      
jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install dependencies for pre-commit hooks
        working-directory: ./
        run: |
          pre-commit install


      - name: Run pre-commit hooks
        working-directory: ./
        run: |
          pre-commit run --all-files
