name: Pre-release check

on:
  workflow_dispatch:
    paths:
      - '**.py'  
      
jobs:
  pre-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install dependencies for pre-commit hooks
        working-directory: ./
        run: |
          pre-commit install


      - name: Run pre-commit hooks
        working-directory: ./
        run: |
          pre-commit run --all-files

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        if: always()
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: pre-release-update
            title: Update pre-release
            commit-message: "Chore(deps): Updating pre-release"
            body: |
              Update 'pre-release'